name: Build Android App Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Install Cordova
      run: npm install -g cordova
      
    - name: Add Android platform
      run: cordova platform add android
      
    - name: Build Android App Bundle
      run: cordova build android --release -- --packageType=bundle
      
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: hexill-android-bundle
        path: platforms/android/app/build/outputs/bundle/release/app-release.aab
